#ifndef APPLE_H
#define APPLE_H

#define APPLE_VEND_SPECIFIC_SET_MODE 0x52

NTSTATUS SetAppleMode(
	INOUT PIU_DEVICE Dev,
	IN APPLE_CONNECTION_MODE Mode
);

APPLE_CONNECTION_MODE GetAppleMode(
	IN PIU_DEVICE Dev
);

UCHAR GetDesiredConfigurationFromAppleMode(
	APPLE_CONNECTION_MODE Mode
);

#endif
