#pragma once

#include "driver.h"

//for ptp interface
#define USB_DEVICE_SUBCLASS_STILL_IMAGE_CAPTURE 1
#define USB_DEVICE_PROTOCOL_PTP 1
//usbmux interface
#define APPLE_USBMUX_SUBCLASS 254
#define APPLE_USBMUX_PROTOCOL 2
//valeria
#define APPLE_VALERIA_SUBCLASS 42
#define APPLE_VALERIA_PROTOCOL 255
//for network interface
#define USB_DEVICE_SUBCLASS_CDC_NCM 0xD
#define USB_DEVICE_SUBCLASS_CDC_DATA 0

typedef enum {
	APPLE_FUNCTION_UNKNOWN,
	APPLE_FUNCTION_PTP,
	APPLE_FUNCTION_USB_MUX,
	APPLE_FUNCTION_CDC_NCM,
	APPLE_FUNCTION_VALERIA
} APPLE_FUNCTION_TYPE, * PAPPLE_FUNCTION_TYPE;

NTSTATUS ActivatePTPFunction(
	PIU_DEVICE Dev,
	WDFCHILDLIST ChildList
);

NTSTATUS ActivateUsbMuxFunction(
	PIU_DEVICE Dev,
	WDFCHILDLIST ChildList
);

NTSTATUS ActivateCdcNcmFunction(
	PIU_DEVICE Dev,
	WDFCHILDLIST ChildList
);
